name: Deploy hexdoc book to Pages
description: Deploys a hexdoc book to GitHub Pages.
author: hexdoc-dev

inputs:
  release:
    description: "Boolean: if the book should be written to the release path (true) or the latest path (false)"
    required: true
  props:
    description: Path to your props file (hexdoc.toml or properties.toml)
    required: false
  subdirectory:
    description: Subdirectory to deploy the book to
    required: false
  site-url:
    description: Set the base site url instead of looking up the current repo's GitHub Pages url
    required: false
  pages-artifact:
    description: Name of the GitHub Pages artifact to download
    required: false
    default: hexdoc-pages
  pages-branch:
    description: Name of the branch used for GitHub Pages
    required: false
    default: gh-pages

runs:
  using: composite
  steps:
    - name: Download Pages artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.pages-artifact }}

    - name: Unzip web book
      shell: bash
      run: |
        mkdir -p _site/src
        unzip site.zip -d _site/src/docs

    - name: Checkout current Pages
      uses: actions/checkout@v4
      continue-on-error: true
      with:
        ref: ${{ inputs.pages-branch }}
        path: _site/dst

    - name: Merge web book
      env:
        HEXDOC_PROPS: ${{ inputs.props }}
        HEXDOC_RELEASE: ${{ inputs.release }}
        HEXDOC_SUBDIRECTORY: ${{ inputs.subdirectory }}
        GITHUB_PAGES_URL: ${{ inputs.site-url }}
      shell: bash
      run: hexdoc ci merge

    - name: Deploy to Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site/dst/docs/${{ inputs.subdirectory }}
        target-folder: docs/${{ inputs.subdirectory }}
        clean: true
        clean-exclude: |
          CNAME
          .gitignore
