name: Deploy hexdoc book to Pages
description: Merges a new version of a hexdoc book into an existing site, then deploys it to GitHub Pages.
author: hexdoc-dev

inputs:
  release:
    description: "Boolean: if the book should be written to the release path (true) or the latest path (false)"
    required: true
  props:
    description: Path to your props file (hexdoc.toml or properties.toml)
    required: false
  subdirectory:
    description: Subdirectory to deploy the book to
    required: false
  site-url:
    description: Set the base site url instead of looking up the current repo's GitHub Pages url
    required: false
  pages-artifact:
    description: Name of the GitHub Pages artifact to download
    required: false
    default: hexdoc-pages
  pages-branch:
    description: Name of the branch used for GitHub Pages
    required: false
    default: gh-pages
  merge:
    description: "Boolean: if hexdoc-dev/actions/merge should be automatically run. Defaults to 'true'. Set to 'false' if you want to use a specific version of that action"
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    # TODO: https://github.com/orgs/community/discussions/41927
    - if: inputs.merge == 'true'
      uses: hexdoc-dev/actions/merge@v1
      with:
        release: ${{ inputs.release }}
        props: ${{ inputs.props }}
        subdirectory: ${{ inputs.subdirectory }}
        site-url: ${{ inputs.site-url }}
        pages-artifact: ${{ inputs.pages-artifact }}
        pages-branch: ${{ inputs.pages-branch }}

    - name: Deploy to Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: ${{ inputs.pages-branch }}
        folder: _site/dst/docs/${{ inputs.subdirectory }}
        target-folder: docs/${{ inputs.subdirectory }}
        clean: true
        clean-exclude: |
          CNAME
          .gitignore
