name: Set up hexdoc actions
description: Runs helpful setup for other hexdoc actions.
author: hexdoc-dev

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.11"
  uv-version:
    description: UV version to install
    required: false
  pip-extras:
    description: Pip extras for your package (eg. "[dev]")
    required: false
  pip-args:
    description: Extra arguments when running `uv pip install`
    required: false

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - uses: yezz123/setup-uv@v4
      with:
        uv-version: ${{ inputs.uv-version }}

    - name: Install Python packages
      shell: bash
      run: uv pip install --system -e .${{ inputs.pip-extras }} ${{ inputs.pip-args }}
