name: Release actions

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: object-Object/action-update-semver@v1.2.1-fix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
